site_name: dustyfargoadsg
repo_url: https://github.com/charango/dustyfargoadsg
repo_name: dustyfargoadsg
site_author: Clément Baruteau

nav:
- Introduction: index.md
- Quickstart: quickstart.md
- Dust particles: dust_particles.md
- Dust fluid: dust_fluid.md

theme:
  name: material
  palette:
  - scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: teal
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode

markdown_extensions:
- admonition
#  - pymdownx.details
#  - pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.arithmatex:
    generic: true
- attr_list
- md_in_html
- footnotes

plugins:
- include-markdown
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          heading_level: 0

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
- stylesheets/extra.css
